### ISSUE TITLE
Thoughts on always sending 200 status code?

### ISSUE THREAD

**Issue by ganemone** [fusionjs/fusion-plugin-rpc#18]
HTTP status codes don't translate nicely to the web rpc pattern. We currently send a 400 status code on RPC failure, however this doesn't really make any sense. From the RPC framework perspective, the request succeeded. We could potentially send some error status code for serialization / deserialization errors, but apart from that I think we should simply default to a 200 status code, and allow the user to override it via the `ctx` argument passed to the rpc handler.

Thoughts?

**Comment by AlexMSmithCA** [comment]
It would be nice if we were compliant with an RPC over HTTP spec here.  I'm not sure if this is still relevant (from 2008 with broken links), but there may be valid HTTP status for [different RPC protocol failures](http://www.jsonrpc.org/historical/json-rpc-over-http.html#response-codes).  And for everything else, default to 200.

**Comment by ganemone** [comment]
Sounds good
